language: java
env:
  global:
    - CATALINA_PID=/tmp/tomcat.pid
    - CATALINA_OUT=/tmp/tomcat.log
    - CATALINA_OPTS=-DUAA_PROFILE=local
before_install:
  - phantomjs --version
  - git pull --unshallow
  - wget -O tomcat.tar.gz http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.52/bin/apache-tomcat-7.0.52.tar.gz
  - $TRAVIS_BUILD_DIR/.clone_matched_uaa_branch.sh
install:
  - cd $TRAVIS_BUILD_DIR/uaa
  - mvn -U clean --quiet -DskipTests=true
  - mvn -U install --quiet -DskipTests=true
  - cd $TRAVIS_BUILD_DIR
  - mvn -U clean --quiet -DskipTests=true
  - mvn -U install --quiet -DskipTests=true
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p target/tomcat
  - tar zvxf tomcat.tar.gz -C target/tomcat --strip-components 1
  - rm -rf target/tomcat/webapps/*
  - cd $TRAVIS_BUILD_DIR/uaa
  - mvn -Dwar.exploded.dir=$TRAVIS_BUILD_DIR/target/tomcat/webapps/uaa -pl uaa war:exploded
  - mvn -Dwar.exploded.dir=$TRAVIS_BUILD_DIR/target/tomcat/webapps/app -pl samples/app war:exploded
  - mvn -Dwar.exploded.dir=$TRAVIS_BUILD_DIR/target/tomcat/webapps/api -pl samples/api war:exploded
  - cd $TRAVIS_BUILD_DIR
  - mvn -Dwar.exploded.dir=$TRAVIS_BUILD_DIR/target/tomcat/webapps/login -pl login-server war:exploded
script:
  - ./.run-script.sh start
  - mvn -Dtest=org.cloudfoundry.identity.uaa.integration.* -DfailIfNoTests=false test --quiet
  - cd login-server-integration-tests && mvn verify --quiet
  - cd $TRAVIS_BUILD_DIR
  - ./.run-script.sh stop
  - mvn -Dspring.profiles.active=$TESTENV test --quiet
after_failure:
  - cat $CATALINA_OUT
after_script:
  - rm -rf tomcat
  - rm -f tomcat.tar.gz
